import React from 'react';
import FaqsImage from "../assets/img/faqs.png";

const FAQsPage: React.FC = () => {
  const faqs = [
    {
      question: 'How are shipment quotes generated?',
      answer: 'Quotes are generated by an algorithm that accounts for variations in distance and travel time.',
    },
    {
      question: 'How are rates determined for shipping services?',
      answer: 'Rates are determined based on factors such as shipment distance, size, weight, market demand, fuel costs, and carrier availability.',
    },
    {
      question: 'What should I do if I have an issue after normal business hours?',
      answer: 'Freight Broker is here to help you resolve issues no matter the time of day. Solution oriented, Friendly Agents and dispatches. We provide individualized, personal focused transportation service.',
    },
    {
      question: 'How many loads per day does Freight Broker move?',
      answer: 'We can help match you with over 10,000 loads per day from more than 14,000 shippers in our network. Our wide range of equipment ensures that we are well equipped to handle shipment of all shapes and sizes. Poseidon is your quality direct delivery carrier.',
    },
  ];

  return (
    <div className="bg-white flex flex-col items-center lg:flex-row lg:items-start px-4 md:px-8 lg:px-36">
      {/* Image Section */}
      <div className="text-center mb-8 w-full lg:w-auto">
        <div id="features" className="bg-white py-12">
          <div className="max-w-7xl mx-auto px-6 sm:px-8 lg:px-12">
            <div className="text-start">
              <h2 className="mt-4 text-3xl text-gray-600 tracking-wider text-primary font-">
              FAQs
              </h2>
            </div>
          </div>
          {/* Image display with responsive margin and padding */}
          <div className="mt-8 lg:mt-14 flex justify-center lg:pl-32">
          <img
            src={FaqsImage}
            alt="FAQS"
            className="w-[396px] h-[386px] object-cover"
            style={{ width: '396px', height: '386px' }}
          />
        </div>

        </div>
      </div>

        {/* FAQ Section */}
        <div className="lg:w-1/2 lg:mt-32 lg:pl-14">
          {faqs.map((faq, index) => (
            <div key={index} className="mb-6">
              <h2 className="text-xl font-medium text-primary mb-2">{faq.question}</h2>
              <p className="text-gray-500 text-sm font-normal mb-2 text-justify">{faq.answer}</p>
              {index < faqs.length - 1 && <hr className="mt-6 border-light-grey" />}
            </div>
          ))}
        </div>
      </div>
  );
};

export default FAQsPage;
