import React from 'react';
import FaqsImage from "../assets/img/faqs.png";

const FAQsPage: React.FC = () => {
  const faqs = [
    {
      question: 'How are shipment quotes generated?',
      answer: 'Quotes are generated by an algorithm that accounts for variations in distance and travel time.',
    },
    {
      question: 'How are rates determined for shipping services?',
      answer: 'Rates are determined based on factors such as shipment distance, size, weight, market demand, fuel costs, and carrier availability.',
    },
    {
      question: 'What should I do if I have an issue after normal business hours?',
      answer: 'Freight Broker is here to help you resolve issues no matter the time of day. Solution oriented, Friendly Agents and dispatches. We provide individualized, personal focused transportation service.',
    },
    {
      question: 'How many loads per day does Freight Broker move?',
      answer: 'We can help match you with over 10,000 loads per day from more than 14,000 shippers in our network. Our wide range of equipment ensures that we are well equipped to handle shipment of all shapes and sizes. Poseidon is your quality direct delivery carrier.',
    },
  ];

  return (
    <div className="bg-white flex flex-col  px-4 py-8 md:px-8 lg:px-32 lg:py-28">
      <h2 className="text-left text-3xl text-gray-600 tracking-wider text-primary mb-8 lg:px-8">
        FAQs
      </h2>
      <div className="flex flex-col lg:flex-row items-center lg:items-start  lg:px-28">

        {/* Image Section */}
        <div className="text-center mb-8 lg:mb-0 lg:w-1/3 ">
          <img
            src={FaqsImage}
            alt="FAQS"
            className="lg:wfull lg:h-full "
          />
        </div>

        {/* FAQ Section */}
        <div className="lg:w-2/3 ">

          {faqs.map((faq, index) => (
            <div key={index} className="mb-6">
              <h2 className="text-xl font-medium text-primary mb-2">{faq.question}</h2>
              <p className="text-gray-500 text-md font-thin mb-2 text-justify">{faq.answer}</p>
              {index < faqs.length - 1 && <hr className="mt-6 border-light-grey" />}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default FAQsPage;
